single line commands

diff --git a/recipes/recipe.yml b/recipes/recipe.yml
--- a/recipes/recipe.yml
+++ b/recipes/recipe.yml
@@ -258,25 +258,8 @@ modules:
   # Move flatpak setup earlier to catch issues sooner
   - type: script
     snippets:
-      - |
-        SCRIPT_PATH="/etc/skel/.local/share/omadora/bin/omadora-powerprofiles-set"
-        echo '#!/bin/bash
-        profile="$1"
-        if sudo tuned-adm profile "$profile"; then
-            notify-send -a "PowerProfiles" "Power profile set to '"$profile"'"
-        else
-            notify-send -a "PowerProfiles" "Failed to set power profile to '"$profile"'"
-            exit 1
-        fi' > "$SCRIPT_PATH"
-        chmod +x "$SCRIPT_PATH"
-
-  - type: script
-    snippets:
-      - |
-        SCRIPT_PATH="/etc/skel/.local/share/omadora/bin/omadora-powerprofiles-list"
-        echo '#!/bin/bash
-        tuned-adm list | awk '\''/^Available profiles:/ {flag=1; next} /^Current active profile:/ {flag=0} flag && $1 !~ /^[[:space:]]*$/ {print $1}'\''' > "$SCRIPT_PATH"
-        chmod +x "$SCRIPT_PATH"
+      - echo -e "#!/bin/bash\nprofile=\"\$1\"\nif sudo tuned-adm profile \"\$profile\"; then\n    notify-send -a \"PowerProfiles\" \"Power profile set to '\$profile'\"\nelse\n    notify-send -a \"PowerProfiles\" \"Failed to set power profile to '\$profile'\"\n    exit 1\nfi" > /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-set && chmod +x /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-set
+      - echo -e '#!/bin/bash\n# List available tuned profiles and format the output\ntuned-adm list | awk '\''/^Available profiles:/ {flag=1; next} /^Current active profile:/ {flag=0} flag && $1 !~ /^[[:space:]]*$/ {print $1}'\''' > /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-list && chmod +x /etc/skel/.local/share/omadora/bin/omadora-powerprofiles-list
 
   - type: default-flatpaks
     configurations:
